### ISSUE TITLE
ezan problems

### ISSUE THREAD

**Issue by sudis** [barbarbar338/iftar-bot#1]
I was fasting and suddenly I heard the call to prayer. But it was not your call to prayer, it was your bot. Has my fast been broken?

**you re zındık**

**Comment by barbarbar338** [comment]
If you live in Kayseri and its east, it's okay, but if you are in the west, your fast may be broken.  Bot works according to the time of Kayseri 😎

**Comment by Umut-Ozkan** [comment]
puahahha
